### Importing Required Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import StratifiedKFold, train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score,
    classification_report, confusion_matrix
)
import os
from sklearn.ensemble import GradientBoostingClassifier

### Loading Data

In [4]:
drug_interaction=pd.read_csv("drug_id_5693.csv")

cell_feature=pd.read_csv("cell_feature.csv")

drug_feature=pd.read_csv("feature197_300.csv")

### Drug Interaction Dataset Overview

- This dataset contains records of drug pairs tested on specific cell lines.
- Columns:
  - `g_id1`: Identifier for the first drug in the pair.
  - `g_id2`: Identifier for the second drug in the pair.
  - `cell`: The cell line where the drug pair was tested (e.g., `MDAMB468`, `BT549`).
  - `label`: Synergy status of the drug pair on the given cell line.
    - `0` indicates **synergistic** interaction.
    - `1` indicates **non-synergistic** interaction.

In [6]:
drug_interaction.head(3)

   g_id1  g_id2      cell  label
0    192    115  MDAMB468      1
1     16     50     BT549      0
2    162     93     BT549      0

In [7]:
drug_interaction.shape  #The `drug_interaction` dataset contains 5693 rows ie 5693 different interaction dataset

(5693, 4)

### Class Distribution of Synergy Status

In [9]:
drug_interaction.label.value_counts()

label
0    4349
1    1344
Name: count, dtype: int64

### Cell Line Feature Data

- This table contains molecular features associated with each **cell line**.
- The first column identifies the **cell line** (e.g., `MDAMB468`).
- Subsequent columns correspond to gene expression levels

In [11]:
cell_feature.head(3)

,cell,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
0,MDAMB468,32.57,7.69,19.51,11.42,12.93,82.54,19.83,0.07,1.25,...,10.26,15.01,100.27,23.40,7.32,13.72,2.90,5.94,35.27,92.34
1,BT549,40.52,17.08,59.10,32.71,15.08,131.08,26.65,0.00,4.80,...,3.71,6.37,90.65,26.82,2.10,11.53,0.03,1.53,27.28,37.67
2,BT549,40.52,17.08,59.10,32.71,15.08,131.08,26.65,0.00,4.80,...,3.71,6.37,90.65,26.82,2.10,11.53,0.03,1.53,27.28,37.67

### Drug Feature Dataset

- This dataset contains numerical features representing chemical or structural properties of drugs.
- Columns labeled generically (e.g., `Column1.1` to `Column1.300`) correspond to various extracted features or descriptors.
- Each row represents a single drugâ€™s feature vector.

In [13]:
drug_feature.head(3)

,Column1.1,Column1.2,Column1.3,Column1.4,Column1.5,Column1.6,Column1.7,Column1.8,Column1.9,Column1.10,...,Column1.291,Column1.292,Column1.293,Column1.294,Column1.295,Column1.296,Column1.297,Column1.298,Column1.299,Column1.300
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,0,1,0,1,1,0,...,0,0,0,1,1,0,1,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Dataset Summary: Unique Drugs and Cell Lines

- **Total unique drugs:** The count of distinct drugs involved in all drug pairs, combining both drug identifiers (`g_id1` and `g_id2`).
- **Total unique cell lines:** The count of distinct cell lines used in experiments.

In [15]:
# Calculate total unique drugs across both drug columns
total_unique_drugs = len(np.unique(np.concatenate([drug_interaction['g_id1'].unique(), drug_interaction['g_id2'].unique()])))

# Calculate total unique cell lines
total_unique_cells = len(cell_feature['cell'].unique())

# Print the results
print(f"Total unique drugs in dataset: {total_unique_drugs}")
print(f"Total unique cell lines in dataset: {total_unique_cells}")

Total unique drugs in dataset: 197
Total unique cell lines in dataset: 12

### Normalizing cell features

In [17]:
cell_features = cell_feature.drop_duplicates(subset='cell').set_index('cell')

cell_features_numeric = cell_features.apply(pd.to_numeric, errors='coerce')

### Using quantile normalization

In [19]:

def quantile_normalize(df: pd.DataFrame) -> pd.DataFrame:
    sorted_values = np.sort(df.values, axis=0)
    
    mean_values = sorted_values.mean(axis=1)
    
    ranks = df.rank(method='min', axis=0).astype(int) - 1
    
    qn_values = np.zeros(df.shape)
    for col_idx in range(df.shape[1]):
        qn_values[:, col_idx] = mean_values[ranks.iloc[:, col_idx].values]
    
    qn_df = pd.DataFrame(qn_values, index=df.index, columns=df.columns)
    return qn_df


qn_result = quantile_normalize(cell_features_numeric)

print(qn_result)

          ENSG00000116237  ENSG00000162413  ENSG00000171603  ENSG00000160049  \
cell
MDAMB468        24.153155        21.444612        18.880660        24.153155
BT549           30.831625        42.514990        42.514990        87.035231
ZR751           18.880660        16.163470         9.875010         9.875010
KPL1            13.750629        18.880660        24.153155        27.206593
HS578T          87.035231        35.955964        87.035231        13.750629
HUH7            42.514990        27.206593        27.206593        35.955964
MCF7             9.875010        13.750629        13.750629        18.880660
A549            16.163470         9.875010        21.444612        21.444612
UO31            21.444612        30.831625        30.831625        52.203396
HCC1187         27.206593        87.035231        16.163470        16.163470
ACHN            35.955964        24.153155        35.955964        42.514990
X786O           52.203396        52.203396        52.203396        30.831625

          ENSG00000065526  ENSG00000117118  ENSG00000053371  ENSG00000076864  \
cell
MDAMB468        27.206593        18.880660        16.163470        24.153155
BT549           35.955964        87.035231        24.153155         9.875010
ZR751           13.750629        16.163470        18.880660         9.875010
KPL1            42.514990        21.444612        42.514990        87.035231
HS578T          52.203396        42.514990        87.035231        27.206593
HUH7            21.444612        13.750629        21.444612         9.875010
MCF7            18.880660        24.153155        30.831625        52.203396
A549             9.875010        30.831625        13.750629         9.875010
UO31            16.163470        27.206593        52.203396         9.875010
HCC1187         87.035231         9.875010         9.875010        30.831625
ACHN            24.153155        35.955964        35.955964        35.955964
X786O           30.831625        52.203396        27.206593        42.514990

          ENSG00000070831  ENSG00000133216  ...  ENSG00000156299  \
cell                                        ...
MDAMB468        18.880660        35.955964  ...        87.035231
BT549           87.035231         9.875010  ...        30.831625
ZR751           52.203396         9.875010  ...        24.153155
KPL1            27.206593         9.875010  ...        42.514990
HS578T          21.444612         9.875010  ...        18.880660
HUH7            16.163470         9.875010  ...         9.875010
MCF7            24.153155        24.153155  ...        35.955964
A549            30.831625        35.955964  ...        16.163470
UO31            13.750629        87.035231  ...        27.206593
HCC1187          9.875010        52.203396  ...        52.203396
ACHN            35.955964        27.206593  ...        21.444612
X786O           42.514990        27.206593  ...         9.875010

          ENSG00000142166  ENSG00000159228  ENSG00000159231  ENSG00000183527  \
cell
MDAMB468        87.035231        35.955964        35.955964        42.514990
BT549           18.880660        30.831625        52.203396        16.163470
ZR751           30.831625         9.875010        24.153155         9.875010
KPL1            13.750629        18.880660        18.880660        30.831625
HS578T           9.875010        87.035231        87.035231        18.880660
HUH7            21.444612        13.750629         9.875010        27.206593
MCF7            35.955964        16.163470        21.444612        52.203396
A549            42.514990        52.203396        13.750629        35.955964
UO31            24.153155        21.444612        16.163470        13.750629
HCC1187         16.163470        24.153155        42.514990        21.444612
ACHN            27.206593        42.514990        27.206593        24.153155
X786O           52.203396        27.206593        30.831625        87.035231

          ENSG00000182093  ENSG00000182240  ENSG00000157617  ENSG00000160208  \
cell
MDAMB468        24.153155        52.203396        87.035231        52.203396
BT549           16.163470        18.880660        21.444612        42.514990
ZR751           21.444612         9.875010        16.163470         9.875010
KPL1            18.880660        30.831625         9.875010        16.163470
HS578T          52.203396        27.206593        35.955964        13.750629
HUH7            27.206593         9.875010        16.163470        35.955964
MCF7            35.955964         9.875010        13.750629        18.880660
A549            30.831625        21.444612        24.153155        30.831625
UO31            87.035231        42.514990        30.831625        24.153155
HCC1187          9.875010        24.153155        42.514990        27.206593
ACHN            13.750629        35.955964        52.203396        21.444612
X786O           42.514990        87.035231        27.206593        87.035231

          ENSG00000141959
cell
MDAMB468        30.831625
BT549           16.163470
ZR751           13.750629
KPL1            42.514990
HS578T          87.035231
HUH7            27.206593
MCF7            52.203396
A549             9.875010
UO31            21.444612
HCC1187         35.955964
ACHN            18.880660
X786O           24.153155

[12 rows x 954 columns]

In [20]:
cell_features=qn_result

### Scaling Cell Features Using Min-Max Normalization

In [22]:

scaler = MinMaxScaler()

cell_feature_scaled = scaler.fit_transform(cell_features)

In [23]:
cell_features = pd.DataFrame(cell_feature_scaled, index=cell_features.index, columns=cell_features.columns)
cell_features

,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,ENSG00000133216,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
cell,,,,,,,,,,,,,,,,,,,,,
MDAMB468,0.185045,0.149943,0.116714,0.185045,0.224618,0.116714,0.081499,0.185045,0.116714,0.338010,...,1.000000,1.000000,0.338010,0.338010,0.423016,0.185045,0.548578,1.000000,0.548578,0.271599
BT549,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,0.185045,0.000000,1.000000,0.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
ZR751,0.116714,0.081499,0.000000,0.000000,0.050228,0.081499,0.116714,0.000000,0.548578,0.000000,...,0.185045,0.271599,0.000000,0.185045,0.000000,0.149943,0.000000,0.081499,0.000000,0.050228
KPL1,0.050228,0.116714,0.185045,0.224618,0.423016,0.149943,0.423016,1.000000,0.224618,0.000000,...,0.423016,0.050228,0.116714,0.116714,0.271599,0.116714,0.271599,0.000000,0.081499,0.423016
HS578T,1.000000,0.338010,1.000000,0.050228,0.548578,0.423016,1.000000,0.224618,0.149943,0.000000,...,0.116714,0.000000,1.000000,1.000000,0.116714,0.548578,0.224618,0.338010,0.050228,1.000000
HUH7,0.423016,0.224618,0.224618,0.338010,0.149943,0.050228,0.149943,0.000000,0.081499,0.000000,...,0.000000,0.149943,0.050228,0.000000,0.224618,0.224618,0.000000,0.081499,0.338010,0.224618
MCF7,0.000000,0.050228,0.050228,0.116714,0.116714,0.185045,0.271599,0.548578,0.185045,0.185045,...,0.338010,0.338010,0.081499,0.149943,0.548578,0.338010,0.000000,0.050228,0.116714,0.548578
A549,0.081499,0.000000,0.149943,0.149943,0.000000,0.271599,0.050228,0.000000,0.271599,0.338010,...,0.081499,0.423016,0.548578,0.050228,0.338010,0.271599,0.149943,0.185045,0.271599,0.000000
UO31,0.149943,0.271599,0.271599,0.548578,0.081499,0.224618,0.548578,0.000000,0.050228,1.000000,...,0.224618,0.185045,0.149943,0.081499,0.050228,1.000000,0.423016,0.271599,0.185045,0.149943
HCC1187,0.224618,1.000000,0.081499,0.081499,1.000000,0.000000,0.000000,0.271599,0.000000,0.548578,...,0.548578,0.081499,0.185045,0.423016,0.149943,0.000000,0.185045,0.423016,0.224618,0.338010
ACHN,0.338010,0.185045,0.338010,0.423016,0.185045,0.338010,0.338010,0.338010,0.338010,0.224618,...,0.149943,0.224618,0.423016,0.224618,0.185045,0.050228,0.338010,0.548578,0.149943,0.116714
X786O,0.548578,0.548578,0.548578,0.271599,0.271599,0.548578,0.224618,0.423016,0.423016,0.224618,...,0.000000,0.548578,0.224618,0.271599,1.000000,0.423016,1.000000,0.224618,1.000000,0.185045

### Preparing Cell Features for Integration with Drug Interaction Data

In [25]:
cell_feature_dict = cell_features.to_dict(orient='index')

In [26]:
cell_feature_dict.keys()

dict_keys(['MDAMB468', 'BT549', 'ZR751', 'KPL1', 'HS578T', 'HUH7', 'MCF7', 'A549', 'UO31', 'HCC1187', 'ACHN', 'X786O'])

### Appending Cell Features to Drug Interaction Dataset
- Merge or join cell line feature data with the drug interaction dataset.
- The merging key is the `cell` identifier common to both datasets.

In [28]:
drug_interaction['cell_features'] = drug_interaction['cell'].map(cell_feature_dict)

In [29]:
drug_interaction

,g_id1,g_id2,cell,label,cell_features
0,192,115,MDAMB468,1,"{'ENSG00000116237': 0.18504541110447711, 'ENSG..."
1,16,50,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."
2,162,93,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."
3,55,10,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."
4,24,20,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."
...,...,...,...,...,...
5688,194,45,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."
5689,44,91,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."
5690,33,86,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."
5691,69,68,HS578T,0,"{'ENSG00000116237': 1.0000000000000002, 'ENSG0..."
5692,58,109,BT549,0,"{'ENSG00000116237': 0.27159868416137034, 'ENSG..."

### Expanding and Setting Cell Features in Drug Interaction Dataset

- The `cell_features` column in the `drug_interaction` dataframe contains nested data (e.g., a list or dictionary).
- `apply(pd.Series)` is used to expand each element of `cell_features` into separate columns.
- The original `cell_features` column is dropped.

In [31]:
cell_features_expanded = drug_interaction['cell_features'].apply(pd.Series)

drug_interaction = pd.concat([drug_interaction.drop(columns=['cell_features']), cell_features_expanded], axis=1)
drug_interaction

,g_id1,g_id2,cell,label,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
0,192,115,MDAMB468,1,0.185045,0.149943,0.116714,0.185045,0.224618,0.116714,...,1.000000,1.000000,0.338010,0.338010,0.423016,0.185045,0.548578,1.000000,0.548578,0.271599
1,16,50,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
2,162,93,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
3,55,10,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
4,24,20,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5688,194,45,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
5689,44,91,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
5690,33,86,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499
5691,69,68,HS578T,0,1.000000,0.338010,1.000000,0.050228,0.548578,0.423016,...,0.116714,0.000000,1.000000,1.000000,0.116714,0.548578,0.224618,0.338010,0.050228,1.000000
5692,58,109,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.116714,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499

In [32]:
drug_interaction.shape

(5693, 958)

### Mapping Drug Features to Drug Interaction Dataset and Replacing IDs with Corresponding Features

In [34]:
drug_feature_dict = drug_feature.to_dict(orient='index')

drug_interaction['g_id1_features'] = drug_interaction['g_id1'].map(drug_feature_dict)
drug_interaction['g_id2_features'] = drug_interaction['g_id2'].map(drug_feature_dict)

In [35]:
drug_interaction.head()

,g_id1,g_id2,cell,label,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,...,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959,g_id1_features,g_id2_features
0,192,115,MDAMB468,1,0.185045,0.149943,0.116714,0.185045,0.224618,0.116714,...,0.338010,0.338010,0.423016,0.185045,0.548578,1.000000,0.548578,0.271599,"{'Column1.1': 0, 'Column1.2': 0, 'Column1.3': ...","{'Column1.1': 1, 'Column1.2': 1, 'Column1.3': ..."
1,16,50,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499,"{'Column1.1': 0, 'Column1.2': 0, 'Column1.3': ...","{'Column1.1': 0, 'Column1.2': 0, 'Column1.3': ..."
2,162,93,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499,"{'Column1.1': 0, 'Column1.2': 0, 'Column1.3': ...","{'Column1.1': 0, 'Column1.2': 1, 'Column1.3': ..."
3,55,10,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499,"{'Column1.1': 1, 'Column1.2': 0, 'Column1.3': ...","{'Column1.1': 0, 'Column1.2': 0, 'Column1.3': ..."
4,24,20,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0.271599,0.548578,0.081499,0.081499,0.116714,0.149943,0.423016,0.081499,"{'Column1.1': 0, 'Column1.2': 0, 'Column1.3': ...","{'Column1.1': 0, 'Column1.2': 0, 'Column1.3': ..."

### Expanding and Setting Cell Features in Drug Interaction Dataset

In [37]:
g_id1_features_expanded = drug_interaction['g_id1_features'].apply(pd.Series).add_prefix('g1_')

g_id2_features_expanded = drug_interaction['g_id2_features'].apply(pd.Series).add_prefix('g2_')

drug_interaction = pd.concat([drug_interaction.drop(columns=['g_id1_features', 'g_id2_features']), 
                       g_id1_features_expanded, 
                       g_id2_features_expanded], axis=1)

In [38]:
drug_interaction.head()

,g_id1,g_id2,cell,label,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,...,g2_Column1.291,g2_Column1.292,g2_Column1.293,g2_Column1.294,g2_Column1.295,g2_Column1.296,g2_Column1.297,g2_Column1.298,g2_Column1.299,g2_Column1.300
0,192,115,MDAMB468,1,0.185045,0.149943,0.116714,0.185045,0.224618,0.116714,...,1,1,0,0,0,0,0,1,0,0
1,16,50,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0,0,0,0,0,0,0,0,0,0
2,162,93,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,1,1,0,0,0,1,0,1,0,0
3,55,10,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0,0,0,0,0,0,1,0,1,0
4,24,20,BT549,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,...,0,0,0,1,1,0,1,0,0,0

In [39]:
drug_interaction.drop(columns=['g_id1','g_id2','cell'],inplace=True)
drug_interaction.head()

,label,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,...,g2_Column1.291,g2_Column1.292,g2_Column1.293,g2_Column1.294,g2_Column1.295,g2_Column1.296,g2_Column1.297,g2_Column1.298,g2_Column1.299,g2_Column1.300
0,1,0.185045,0.149943,0.116714,0.185045,0.224618,0.116714,0.081499,0.185045,0.116714,...,1,1,0,0,0,0,0,1,0,0
1,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,0.185045,0.000000,1.000000,...,0,0,0,0,0,0,0,0,0,0
2,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,0.185045,0.000000,1.000000,...,1,1,0,0,0,1,0,1,0,0
3,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,0.185045,0.000000,1.000000,...,0,0,0,0,0,0,1,0,1,0
4,0,0.271599,0.423016,0.423016,1.000000,0.338010,1.000000,0.185045,0.000000,1.000000,...,0,0,0,1,1,0,1,0,0,0

### Splitting Features and Target Variable

- `X` contains all columns except the `label`, i.e., it includes drug features and cell features used for prediction.
- `y` stores the `label` column, which represents the synergy class â€” 0 for synergistic and 1 for non-synergistic interactions.

In [41]:
X = drug_interaction.drop(columns=['label'])
y = drug_interaction['label']

### Splitting Dataset into Training and Testing Sets

- Split the feature matrix `X` and target vector `y` into training and testing subsets.

### Training with GradientBoostingClassifier Model and Evaluating via Stratified K-Fold Cross-Validation

In [44]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

accuracy_list = []
precision_list = []
recall_list = []
f1_list = []

### GradientBoostingClassifier model Training and Evaluation Using Stratified K-Fold Cross-Validation

This code performs 5-fold stratified cross-validation to evaluate the GradientBoostingClassifier model with balanced class weights.

- The dataset is split into 5 folds maintaining the original class distribution in each fold.
- For each fold:
  - Train on 4 folds and test on the remaining fold.
  - Calculate performance metrics: Accuracy, Weighted Precision, Weighted Recall, and Weighted F1-Score.
  - Display the confusion matrix with a heatmap visualization.
  - Print a detailed classification report to analyze per-class performance.
- This approach helps provide a robust estimate of model performance while addressing potential class imbalance.
### Training and Evaluating Decision with Optimized Hyperparameters

In [46]:

fold = 1
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    accuracy_list.append(acc)
    precision_list.append(prec)
    recall_list.append(rec)
    f1_list.append(f1)

    print(f"\nFold {fold}:")
    print(f"  Accuracy           = {acc:.4f}")
    print(f"  Weighted Precision = {prec:.4f}")
    print(f"  Weighted Recall    = {rec:.4f}")
    print(f"  Weighted F1-score  = {f1:.4f}")

    cm = confusion_matrix(y_test, y_pred)
    print("  Confusion Matrix:")
    print(cm)

    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f'Confusion Matrix - Fold {fold}')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
      

    
    plt.savefig(os.path.join('img', f'confusion_matrix_fold_{fold}_after_tuning.png'))    
    plt.close()

    print("\nDetailed Classification Report:")
    print(classification_report(y_test, y_pred, digits=4))

    fold += 1

Fold 1:
  Accuracy           = 0.7752
  Weighted Precision = 0.7409
  Weighted Recall    = 0.7752
  Weighted F1-score  = 0.7325
  Confusion Matrix:
[[828  42]
 [214  55]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0     0.7946    0.9517    0.8661       870
           1     0.5670    0.2045    0.3005       269

    accuracy                         0.7752      1139
   macro avg     0.6808    0.5781    0.5833      1139
weighted avg     0.7409    0.7752    0.7325      1139


Fold 2:
  Accuracy           = 0.7796
  Weighted Precision = 0.7511
  Weighted Recall    = 0.7796
  Weighted F1-score  = 0.7272
  Confusion Matrix:
[[843  27]
 [224  45]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0     0.7901    0.9690    0.8704       870
           1     0.6250    0.1673    0.2639       269

    accuracy                         0.7796      1139
   macro avg     0.7075    0.5681    0.5672      1139
weighted avg     0.7511    0.7796    0.7272      1139


Fold 3:
  Accuracy           = 0.7849
  Weighted Precision = 0.7593
  Weighted Recall    = 0.7849
  Weighted F1-score  = 0.7405
  Confusion Matrix:
[[838  32]
 [213  56]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0     0.7973    0.9632    0.8725       870
           1     0.6364    0.2082    0.3137       269

    accuracy                         0.7849      1139
   macro avg     0.7168    0.5857    0.5931      1139
weighted avg     0.7593    0.7849    0.7405      1139


Fold 4:
  Accuracy           = 0.7768
  Weighted Precision = 0.7439
  Weighted Recall    = 0.7768
  Weighted F1-score  = 0.7286
  Confusion Matrix:
[[835  34]
 [220  49]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0     0.7915    0.9609    0.8680       869
           1     0.5904    0.1822    0.2784       269

    accuracy                         0.7768      1138
   macro avg     0.6909    0.5715    0.5732      1138
weighted avg     0.7439    0.7768    0.7286      1138


Fold 5:
  Accuracy           = 0.7707
  Weighted Precision = 0.7297
  Weighted Recall    = 0.7707
  Weighted F1-score  = 0.7107
  Confusion Matrix:
[[843  27]
 [234  34]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0     0.7827    0.9690    0.8659       870
           1     0.5574    0.1269    0.2067       268

    accuracy                         0.7707      1138
   macro avg     0.6701    0.5479    0.5363      1138
weighted avg     0.7297    0.7707    0.7107      1138

### Calculating and Printing Average Performance Metrics Across All 5 Folds

In [48]:
print("\n=== Average Across 5 Folds ===")
print(f"wt.Avg Accuracy       = {np.mean(accuracy_list):.4f}")
print(f"wt.Avg Macro Precision= {np.mean(precision_list):.4f}")
print(f"wt.Avg Macro Recall   = {np.mean(recall_list):.4f}")
print(f"wt.Avg Macro F1-score = {np.mean(f1_list):.4f}")

=== Average Across 5 Folds ===
wt.Avg Accuracy       = 0.7774
wt.Avg Macro Precision= 0.7450
wt.Avg Macro Recall   = 0.7774
wt.Avg Macro F1-score = 0.7279

### Calculation of ROC AUC and Precision-Recall AUC (PR AUC)

In [50]:
model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
y_probs = model.predict_proba(X_test)[:, 1]

In [52]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_test, y_probs)
print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.708204480637735

In [53]:
output_dir = 'img'

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, thresholds = roc_curve(y_test, y_probs)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random Classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.grid(True)
plt.savefig(os.path.join(output_dir, f'rocauc.png'))    
plt.close()

In [54]:
from sklearn.metrics import average_precision_score

pr_auc = average_precision_score(y_test, y_probs)
print("PR-AUC Score:", pr_auc)

PR-AUC Score: 0.4722136102130261

In [55]:
from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

precision, recall, thresholds = precision_recall_curve(y_test, y_probs)

plt.figure(figsize=(8,6))
plt.plot(recall, precision, label=f'Logistic Regression (PR-AUC = {pr_auc:.2f})')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend()
plt.grid(True)
plt.savefig(os.path.join(output_dir, f'prauc.png'))    
plt.close()